name: Cypress Tests

on:
  push:
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress (UI + API)
        uses: cypress-io/github-action@v6
        with:
          install: true
          command: npm test
        env:
          SAUCE_USER: ${{ secrets.SAUCE_USER }}
          SAUCE_PASS: ${{ secrets.SAUCE_PASS }}
